name: spend_wise
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.3.0
  font_awesome_flutter: ^11.0.0
  intl: ^0.20.3
  skeletonizer: ^2.1.3
  supabase_flutter: ^2.16.0
  flutter_native_splash: ^2.4.8
  sqflite: ^2.4.3
  path_provider: ^2.1.6
  connectivity_plus: ^7.3.1
  uuid: ^4.6.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/coins_padded.png"
  image_path_ios: "assets/coins_ios_padded.png"
  adaptive_icon_background: "#131924"
  adaptive_icon_foreground: "assets/coins_padded.png"

flutter_native_splash:
  color: "#F1F5F9"
  color_dark: "#05080E"
  image: "assets/coins_padded.png"
  image_dark: "assets/coins_padded.png"
  android: true
  ios: true

